GET http://localhost:3000/api/plants

###
POST http://localhost:3000/api/plants
Content-Type: application/json

{
    "plantName": "Day",
    "wateringDate": "14",
    "lastWateringDate": "2022/09/30",
    "creatorId": "J",
    "imageUrl": "image3.png"
}

###
PUT http://localhost:3000/api/plants/2
Content-Type: application/json

{
    "plantName": "Night"
}