GET http://localhost:3001/api/plants

###
GET http://localhost:3001/api/notification/subscription/

###
POST http://localhost:3001/api/notification/subscription  
Content-Type: application/json

{
    
    "userid": "Day9",
    "subscription": {
        "5":"1",
        "2":"3"
    }
    
}
###

POST http://localhost:3001/api/plants
Content-Type: application/json

{
    "id":1,
    "plantName": "Day5",
    "wateringDate": "14",
    "lastWateringDate": "2022/09/30",
    "creatorId": "sy95_055@naver.com",
    "imageUrl": "http://localhost:3001/uploads/img/plant11666010660003.png"
}

###
PUT http://localhost:3000/api/plants/2
Content-Type: application/json

{
    "plantName": "Night"
}

###
DELETE http://localhost:3001/api/plants/32

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "userid": "Day@naver.com",
    "userpassword": "12324234",
    "username": "SYP"    
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "userid": "Day@naver.com",
    "userpassword": "12324234"
}

###
GET http://localhost:3001/api/auth/id
